---
abstract: 'plagger like plugin feature for Moose'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Plaggerize
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  Moose: 0.70
  Scalar::Util: 1.19
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
